### ISSUE TITLE
Error in compiling 

### ISSUE THREAD

**Issue by ThingUroboros** [dosemu2/fdpp#136]
**Problem with make** 
clang++ -std=c++11 -c -fno-threadsafe-statics -fpic -iquote /home/martin/Dokumenty/EMULACE/DOSEMU/fdpp/fdpp/fdpp/../hdr -DI386 -DWITHFAT32 -I . -I /home/martin/Dokumenty/EMULACE/DOSEMU/fdpp/fdpp/include/fdpp -I /home/martin/Dokumenty/EMULACE/DOSEMU/fdpp/fdpp/kernel/ -I /home/martin/Dokumenty/EMULACE/DOSEMU/fdpp/fdpp/fdpp -DFDPPDATADIR=/usr/local/share/fdpp -DKRNL_NAME=fdppkrnl.sys -DKRNL_MAP_NAME=fdppkrnl.map -DKERNEL_VERSION="1.0rc1 [GIT: `git describe`]" -Wall -ggdb3 -O2 -DDEBUG -Wno-format-invalid-specifier -o thunks.o /home/martin/Dokumenty/EMULACE/DOSEMU/fdpp/fdpp/fdpp/thunks.cc
In file included from /home/martin/Dokumenty/EMULACE/DOSEMU/fdpp/fdpp/fdpp/thunks.cc:621:
./thunk_asms.h:1:1: error: C++ requires a type specifier for all declarations
_THUNK_P_0_v(13, fl_readkey, _TFLG_NONE)
^
./thunk_asms.h:1:41: error: expected ';' after top level declarator
_THUNK_P_0_v(13, fl_readkey, _TFLG_NONE)

**I have Linux mint 19.3** 

**gcc -v**
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.5.0-3ubuntu1~18.04' --with-Thread 

 **g++ -v**
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)

**Comment by stsp** [comment]
gcc/g++ have nothing to do with that.
clang/clang++ does.
Anyway, can this be a forgotten "make clean"
or alike? When did that start to happen?
If nothing helps, please archive the entire
build dir with error, and mail it to me.

**Comment by ThingUroboros** [comment]
clang++ -v
clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/8
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0
Candidate multilib: .;@m64
Selected multilib: .;@m64

I use git clone https://github.com/dosemu2/fdpp.git
OK i send you archive
[fdpp.zip](https://github.com/dosemu2/fdpp/files/4510624/fdpp.zip)

**Comment by stsp** [comment]
Should now be fixed, please test.
