### ISSUE TITLE
dont recreate CDS after config

### ISSUE THREAD

**Issue by stsp** [dosemu2/fdpp#140]
DOSes recreate CDS after processing
config.sys, effectively disabling the redirections.
emufs.com is a way around that.
But we can just stop recreating CDS
and fare well.

**Comment by andrewbird** [comment]
But how will you deal with `device=blockdriver.sys` etc, will you force CDS size to always be 26?

**Comment by stsp** [comment]
What do you mean?

**Comment by andrewbird** [comment]
It's probably very unusual that FDPP will load block device drivers in config.sys, but I suppose ramdisks and cdroms are possible. Any loaded block device drivers which declare units help to determine the size of the CDS array (lastdrive). So I guess you'll have to force lastdrive to be 26 to allow for any new disks? Will you still optionally move it high?

**Comment by stsp** [comment]
I am not sure I understand.
You can set lastdrive in config.sys,
and if you dont - the default value
is used. Why should I infer lastdrive
from the amount of loaded drives?

**Comment by andrewbird** [comment]
Because CDS size is set from the highest of three inputs, not necessarily the value set by lastdrive in config.sys:
- 5
- number of block devices detected (includes those added by drivers in config.sys)
- lastdrive value

That's why CDS is traditionally recreated after processing config.sys.

**Comment by stsp** [comment]
And what of the above prevents us
from initializing the first entries with
the already created ones?
Also I guess 5 should be replaced
by 10 or more.

**Comment by andrewbird** [comment]
> And what of the above prevents us
from initializing the first entries with
the already created ones?

Oh is that your intention, I thought you were just going to avoid recreating the CDS? This idea of initialising a new one from the current state seems fine.

**Comment by stsp** [comment]
This is an implementation details. :)
I can as well just realloc the original
array, no?

**Comment by andrewbird** [comment]
> I can as well just realloc the original
array, no?

I'd be surprised if there were free space following it, unless of course you oversize the initial one and then resize it down.

**Comment by stsp** [comment]
realloc() can move. :)

**Comment by stsp** [comment]
Actually see here:
https://github.com/dosemu2/fdpp/blob/master/kernel/main.c#L356
It is over-sized even in freedos
(unless I wrote that line myself... which I don't remember)

**Comment by andrewbird** [comment]
That line seems to be at least 8 years old in FreeDOS kernel, I guess nobody actually cares about how much memory is used during boot, only what's free afterwards. Snyway it all sounds good for your plan then.

**Comment by stsp** [comment]
You can do that too if you want.
