### ISSUE TITLE
Newline before entries in descript.ion

### ISSUE THREAD

**Issue by stuaxo** [dosemu2/fdpp#141]
I was browsing some ancient directories of mine that have descriptions, FDPP shows the entries, but it puts in a newline between the filename and description:

This is probably not intended, and looks a bit strange:

![image](https://user-images.githubusercontent.com/179677/82106040-897d8200-9716-11ea-8b6c-805ee151448b.png)

**Comment by andrewbird** [comment]
I've never used `descript.ion` files, but aren't they interpreted and displayed by `command.com`, which judging from the output above is FreeCOM?

**Comment by stsp** [comment]
Yes, I think its freecom.

**Comment by stuaxo** [comment]
Cheers :)
