### ISSUE TITLE
dsk.c:694:48: warning: overlapping comparisons always evaluate to true [-Wtautological-overlap-compare]

### ISSUE THREAD

**Issue by JL2210** [dosemu2/fdpp#142]
https://github.com/dosemu2/fdpp/blob/b98571a131de0c3b5688c987d7cb61384d96ead2/kernel/dsk.c#L694

This expression always evaluates to true. Clang 10 warned about it.

Not sure what the fix is but I figured I should point it out.

```
dsk.c:694:48: warning: overlapping comparisons always evaluate to true [-Wtautological-overlap-compare]
          if ((extended_BPB_signature != 0x29) || (extended_BPB_signature != 0x28))
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by andrewbird** [comment]
Looks like it should be `&&` not `||`.

**Comment by stsp** [comment]
Thanks!
Good catch.
