### ISSUE TITLE
switch to TINY memory model

### ISSUE THREAD

**Issue by stsp** [dosemu2/fdpp#144]
This way all the hacks for
SEG "emulation", as well as
the linker script complexity,
will go away.
It will then be possible to use
lld linker instead of bfd.

**Comment by andrewbird** [comment]
Not sure if your recent changes have broken things for Dosemu, see https://travis-ci.com/github/andrewbird/dosemu2/builds/187655343
For me it's no hassle as I've temporarily switched my travis-ci-30 branch to checkout FDPP tag 1.0, but I guess you might want to disable the launchpad packaging of FDPP.
