### ISSUE TITLE
DPMI "kill psp" function behaves differently in fdpp than in FD kernel.sys (or MS-DOS io.sys)

### ISSUE THREAD

**Issue by Baron-von-Riedesel** [dosemu2/fdpp#154]
The dosemu DPMI host has implemented the "kill psp" function ( calling int 0x21 with AH=00, needed to support Win16, at least ).

This function "terminates" a PSP, and then returns to the caller.
If fdpp is used in dosemu2, contents of register SI is destroyed after the call, if FD kernel.sys is used, contents of register SI is unchanged ( I'm refering to register SI only, because that's the register that the HX NE/PE loader DPMILD32.EXE expects to be preserved across the "kill psp" call.) The changed SI register makes HX's DPMILD32.EXE display:

DPMILD32: stack segment of parent destroyed

Here are log excerpts, written by a debug version of dpmild32.exe (this all happens in protected mode!):
1. fdpp
```
dpmildr: task ptr(si) before dos kill=6BF2
dpmildr: calling dos kill
dpmildr: calling dos set PSP, bx=012F si=000C di=0001 [di=0 if 'kill' failed]
dpmildr: internal task ptr(si)=000C parent ss:sp=F1BF:FA75C022
DPMILD32: stack segment of parent destroyed
*** last task terminated (RC=F1BF), will exit now ***
```

2. kernel.sys
```
dpmildr: task ptr(si) before dos kill=6BF2
dpmildr: calling dos kill
dpmildr: calling dos set PSP, bx=012F si=6BF2 di=0001 [di=0 if 'kill' failed]
dpmildr: internal task ptr(si)=6BF2 parent ss:sp=0127:00007F3E
dpmildr: switched to parent psp and stack
dpmildr: app terminated, esi=05090000, edi=7F4E0246, ebp=6BF245E8
dpmildr: ---------------------------------
*** last task terminated (RC=0000), will exit now ***
```

Depending on other settings ( environment variable DPMILDR, load status of HXLDR32.EXE ) the behavior of dosemu after dpmild32 has terminated varies from "everything ok" to "terminate dosemu2". The default, however, is the latter.

**Comment by stsp** [comment]
I don't understand how is this supposed
to work. All registers are restored from
parent_psp:2eh location. So they all can
change.

**Comment by Baron-von-Riedesel** [comment]
> All registers are restored from parent_psp:2eh location. So they all can change.

But I'm sure you already implemented this in dosemu - because Win 3.1 uses this "kill psp", whenever a 16-bit windows application terminates. Does Win 3.1 work with fdpp?

**Comment by stsp** [comment]
> Does Win 3.1 work with fdpp?

Sure as hell it works, yes.
But see msdos.c:old_dos_terminate() in
dosemu sources. It only makes sure the
return point is same. But it doesn't preserve
any registers. I believe they were always
taken from parent stack.

**Comment by Baron-von-Riedesel** [comment]
I looked at the location in msdos.c, but I have to admit that I don't understand it. I see some "selector magic" ( same in hdpmi ), but I cannot find how real-mode code is executed.

The code in hdpmi is simple and easy to understand
```
intr2100:
	pushad
	push es

	push byte ptr _FLATSEL_
	pop es
	mov eax,ss:[dwSDA]
	movzx ebx,word ptr es:[eax].DOSSDA.wPSP	;get current psp in bx
	shl ebx,4

if 1;ife ?32BIT

;--- someone (Win31!) may have converted the parent psp segment to a
;--- selector, but now real-mode DOS will use it (and expect a segment
;--- value); so check if it is really a selector to a valid PSP
;--- and if true, transform it back to a segment

	mov ax,es:[ebx+16h]
	@strout <"#i21,00: parent psp value %X",lf>,bx

	verw ax			;is a valid data selector?
	jnz @F
	push ds
	mov ds,eax
	cmp word ptr ds:[0],20CDh	;points to a PSP?
	pop ds
	jnz @F
	push eax
	call sel2segm
	pop eax
	jc @F
	mov es:[ebx+16h],ax
@@:
endif

	@strout <"#i21,00: will simulate a dos call 4Ch, esp=%lX",lf>, esp
	mov eax, ss:[dwHostSeg]
	shl eax,16
	mov ax,offset callrmintintern_rm_exit
	mov es:[ebx+000Ah], eax
	mov ax,4C00h
	call rmdos
	@strout <"#i21,00: back from real mode, esp=%lX",lf>, esp

intr2100_ex:
	pop es
	popad
	@strout <"#i21,00: exit ebx=%lX esi=%lX edi=%lX ebp=%lX",lf>,ebx,esi,edi,ebp
	ret
```
As you ( hopefully) can see, hdpmi doesn't care at all to what values the real-mode code ( running an int 0x21, ah=4Ch ) has "restored" the register values. The client registers were all PUSHed and POPed.

**Comment by stsp** [comment]
Yes, same here.
And DOS always restores from parent_psp:2eh.
So what is the problem?

**Comment by stsp** [comment]
> The client registers were all PUSHed and POPed.

Ah, wait, this is not what dosemu does,
or ever did. But... windows always worked.
The problem might be elsewhere?

**Comment by Baron-von-Riedesel** [comment]
Could you explain to me where the real-mode code in old_dos_terminate() is executed or triggered? DOS must be called somehow, to close files and similiar stuff.

**Comment by stsp** [comment]
After old_dos_terminate() fixes up PSP,
msdos.c returns MSDOS_RM to dpmi.c,
which means "go ahead to realmode
processing". See dpmi.c:2990. It sets
up realmode stack frame and return
address, and goes to real mode using
the registers prepared by
msdos_pre_exteder().

The actual realmode code it executes
then, is in fdpp sources, in particular
in task.c:return_user(). It does
`do_ret_user(q->ps_stack, vec22);`
which means, use return address
from current PSP and stack from
parent PSP.
I pretty much believe any DOS does
the same. But perhaps SI was corrupted
somewhere in the parent, before the
child was executed? That would look
more like an fdpp bug.

**Comment by Baron-von-Riedesel** [comment]
Ok, I see. That's actually more complicated than with hdpmi, which can synchronously run real-mode code whenever it thinks it's needed.

**Comment by stsp** [comment]
So do you know the expected value of
SI in the parent? Should it always match
the child, or was it just a luck?

**Comment by stsp** [comment]
Would you like to remove pushad/popad
from hdpmi to see if it still works?

**Comment by Baron-von-Riedesel** [comment]
> Would you like to remove pushad/popad from hdpmi to see if it still works?

I did. To my surprise, Windows 3.1 in standard mode still runs fine with hdpmi16.
Even more surprising, even hdpmi32 + dpmild32 run fine. I see in the log that I made no mistake:

```
dpmildr: last task's PSP selector=00CF
dpmildr: task ptr(si) before dos kill=6BF2
dpmildr: calling dos kill
#i21,00: entry ebx=00406BF2 esi=00406BF2 edi=00001000 ebp=00130FE0
#i21,00: parent psp value B2C0
#i21,00: will simulate a dos call 4Ch, esp=0000265C
#i21,00: back from real mode, esp=0000265C
#i21,00: exit ebx=0000031A esi=00406BF2 edi=00001000 ebp=00130FE0
dpmildr: calling dos set PSP, bx=009F si=6BF2 di=0001 [di=0 if 'kill' failed]
dpmildr: internal task ptr(si)=6BF2 parent ss:sp=008F:00007F3E
dpmildr: switched to parent psp and stack
dpmildr: app terminated, esi=05090000, edi=7F4E3246, ebp=6BF245E8
dpmildr: ---------------------------------
*** last task terminated (RC=0000), will exit now ***
```
the lines beginning with '#' are hdpmi32 logs.
I can see that register EBX is changed (modified by hdpmi itself), but ESI, EDI and EBP are unchanged.
How can this be?

**Comment by Baron-von-Riedesel** [comment]
> How can this be?
A possible explanation: DOS checks carefully where the return address at PSP:000A points to. If it lies within a memory block of the terminating PSP then neither the memory block is freed nor the registers restored. That's a question for DOS kernel experts.

**Comment by stsp** [comment]
> I did. To my surprise, Windows 3.1 in standard mode still runs fine with hdpmi16.

In enhanced its going to work too.

> How can this be?

Because the parent took care of that?

> A DOS kernel expert might be able to verify this hypothesis.

No need for a kernel expert here, to just
find out that:
https://github.com/PerditionC/fdkernel/blob/master/kernel/task.c#L529
the only check is for self-parent PSP.
So if your PSP is self-parent, all regs
will be preserved. But also the memory
and the PSP itself, which is likely not
what you want.

So if SI needs to be "the same", you
need to see in the parent why its not
so.

**Comment by Baron-von-Riedesel** [comment]
> to just find out that: https://github.com/PerditionC/fdkernel/blob/master/kernel/task.c#L529

ok, but my tests were with MS-DOS 7.1 (Win98SE) and hdpmi.
And I ensured that the files in the PSP are indeed closed after the call and the PSP is released - and at least ESI, EDI, EBP preserved (EBX is not, as I verified).

**Comment by stsp** [comment]
> ok, but my tests were with MS-DOS 7.1 (Win98SE) and hdpmi.

Thing work under dosemu2+freedos, and
dosemu2 never did any save/restore. Also
windows works fine with fdpp, and that says
a lot.

> preserved (EBX is not, as I verified).

PSP:2eh points to this structure:
https://github.com/PerditionC/fdkernel/blob/master/hdr/pcb.h#L82
So by using a debugger or printfs
you can inspect the image of child
and parent registers, and make sure
they are same (or not).

**Comment by stsp** [comment]
Could you please check if this fixes it:
https://github.com/dosemu2/fdpp/commit/43f2e9b8ebdfb241bba0c7213e4e5f6d06edf5a8

**Comment by Baron-von-Riedesel** [comment]
I installed the current fdpp.
Now, when starting dosemu2, there are quite a few error messages:
unimplemented internal dos function INT2F/1204

So I thought I had to update dosemu2 as well. I tried, but get a make error:

make[2]: *** No rule to make target '/home/sam/dosemu2/src/dosext/dpmi/msdos/segreg.h', needed by 'dpmi.o'.  Stop.

Dosemu in this state ( with the error msgs ) behaves rather strange, at least with Volkov Commander - you can't change into another directory anymore.

**Comment by stsp** [comment]
Try `make realclean`

**Comment by stsp** [comment]
VC  Version 4.99.08 alpha
works fine here.

**Comment by stsp** [comment]
> unimplemented internal dos function INT2F/1204

What program causes those?
Never seen them.

**Comment by stsp** [comment]
What fdpp revision do you have?

**Comment by Baron-von-Riedesel** [comment]
> Try make realclean

Ok, that helped. Thanks!

> What program causes those?
> Never seen them.

I guess it's emufs.sys
Attached a screenshot and log
![Screenshot at 2020-11-30 03-46-03](https://user-images.githubusercontent.com/38952922/100563655-2f619a00-32bf-11eb-8b42-6f979c6a5425.png)
[boot.log.zip](https://github.com/dosemu2/fdpp/files/5613533/boot.log.zip)

.

**Comment by Baron-von-Riedesel** [comment]
After running fdpp "make clean" and then "make", the "unimplemented..." errors disappeared!

**Comment by stsp** [comment]
So is this all fixed?

**Comment by Baron-von-Riedesel** [comment]
> So is this all fixed?

No. I don't know if the HX loader error is fixed, because I get a KVM exit reason=6 error when I start a HX application (doesn't matter if it uses the loader or not ). 

In /etc/dosemu/dosemu.conf, there's still the $_cpu_vm_dpmi = "native" active, and no local .dosemurc.


[boot.log.zip](https://github.com/dosemu2/fdpp/files/5614709/boot.log.zip)

**Comment by stsp** [comment]
No, you changed nothing:
```
CONF: CPU VM set to -1
CONF: CPU VM set to -1 for DPMI
```
Or forgot to uncomment.

Please, stop editing main dosemu.conf.
Create ~/.dosemu/.dosemurc
and there will be no such problems in
the future.

**Comment by andrewbird** [comment]
> Create ~/.dosemu/.dosemurc
and there will be no such problems in
the future.

If we really want people to use this file perhaps it shouldn't be a dotfile?

**Comment by stsp** [comment]
That's what I asked myself many times.
And I'd like to have it that way too, but:
1. ~/.dosemu also has dot.
2. People already use such setup

So maybe its time to switch to
`~/dosemu2/dosemurc` and look into
the old path only for compatibility?

**Comment by andrewbird** [comment]
> ~/.dosemu also has dot.

Yes I think that has to be maintained, but the `.dosemurc` just adds another level of 'hiddenness' that I don't think we need.

`~/.dosemu/dosemurc`, `~/.dosemu/settings.conf` or `~/.dosemu/config` would be my choices, but I guess it's subjective.

**Comment by Baron-von-Riedesel** [comment]
> No, you changed nothing:

Yes, I did. That's in /etc/dosemu/dosemu.conf:

```
# Select cpu virtualization mode.
# "vm86" - use v86 mode via vm86() syscall. Only available on x86-32.
# "kvm" - use KVM, hardware-assisted in-kernel virtual machine.
# "emulated" - use CPU emulator
# "auto" - select whatever works

# $_cpu_vm = "auto"

# Select cpu virtualization mode for DPMI.
# "native" - use native LDT via modify_ldt() syscall.
# "kvm" - use KVM, hardware-assisted in-kernel virtual machine.
# "emulated" - use CPU emulator
# "auto" - select whatever works

$_cpu_vm_dpmi = "native"

```

**Comment by stsp** [comment]
This is because you don't use
`default-configure -d`
to set the build-time defaults.
Anyway, with the local config you
would avoid that.

**Comment by stsp** [comment]
So is PSP killed or not?

**Comment by Baron-von-Riedesel** [comment]
> So is PSP killed or not?
PSP is killed and contents of register SI is not changed. All as it should be.

**Comment by stsp** [comment]
Great.
So as you can see, save/restore is not needed.
And even if some idiot is using the wrong stack
(as before the patch), then just 1 register gets
corrupted.
