### ISSUE TITLE
qemm mft hangs

### ISSUE THREAD

**Issue by stsp** [dosemu2/fdpp#155]
Bisect: 96158d39

**Comment by stsp** [comment]
Out-of-tree bisect: 167cbb5aa
Hmmm!

**Comment by stsp** [comment]
This "fixes" the problem on an out-of-tree commit:
```
--- a/fdpp/kernel.ld
+++ b/fdpp/kernel.ld
@@ -7,7 +7,7 @@ MEMOFS = DOS_PSP * 16;
 /* Mostly a TINY model, but TGROUP is different for relocations */
 PGROUP = DOS_PSP;
 LGROUP = DOS_PSP;
-DGROUP = DOS_PSP;
+DGROUP = (MEMOFS + LOADADDR(.data)) / 16;
 TGROUP = (MEMOFS + LOADADDR(.text)) / 16;
 IGROUP = DOS_PSP;
 I_GROUP = DOS_PSP;
@@ -30,7 +30,7 @@ SECTIONS
     }
 
     /* Target data sections.  */
-    .data ALIGN(LOADADDR(.ltext) + SIZEOF(.ltext), 16): {
+    .data 0 : AT (ALIGN(LOADADDR(.ltext) + SIZEOF(.ltext), 16)) {
                *(_FIXED_DATA)
                *(_BSS)
                *(_DATA)
```

**Comment by stsp** [comment]
Hmm, qemm seems to work if DGROUP > 0x60.
If it is less or equal to 0x60, mft hangs.
This is most definitely the mft bug.

**Comment by andrewbird** [comment]
Why would any program care, or even notice?

**Comment by stsp** [comment]
If someone had an answer for that, this
bug would have been closed. :)
No slightest idea.

**Comment by stsp** [comment]
Except maybe... by getting LoL??

**Comment by stsp** [comment]
Exactly!
Because RBIL says:
```
        Quarterdeck's suggested check for the use of its DOSDATA.SYS or
          DOS-UP.SYS is to test whether the list-of-lists segment is greater
          than the segment of the first memory block
```

Cool...

**Comment by andrewbird** [comment]
How poor is that!?

**Comment by stsp** [comment]
Quite poor, but there is some code
even poorer than that!
For example if I do:
```
--- a/kernel/inthndlr.c
+++ b/kernel/inthndlr.c
@@ -1121,10 +1121,13 @@ dispatch:
 */
       /* ************UNDOCUMENTED************************************* */
       /* Get List of Lists                                            */
-    case 0x52:
-      lr.BX = FP_OFF(__ASMADDR(DPBp));
-      lr.ES = FP_SEG(__ASMADDR(DPBp));
+    case 0x52: {
+      UWORD loff = FP_OFF(__ASMADDR(DPBp));
+      UWORD lseg = FP_SEG(__ASMADDR(DPBp));
+      lr.BX = loff & 0xf;
+      lr.ES = lseg + (loff >> 4);
       break;
+    }
 
     case 0x53:
       /*  DOS 2+ internal - TRANSLATE BIOS PARAMETER BLOCK TO DRIVE PARAM BLOCK */
```

Then MFS stops working...
So we are not any better.

**Comment by andrewbird** [comment]
So I wonder if it's doing some quarterdeck specific stuff at the point of hang. I don't know what the address of LoL is, but if it's paragraph aligned could you return a higher seg:ofs in int21/52 that equals the same address?

**Comment by stsp** [comment]
See above: MFS stops working.

**Comment by stsp** [comment]
```
    if (lol_hi != sda_hi) {
        ds_printf("INT21: redirector disabled as lol and sda segments differ\n")
;
        _post_msdos();
        return 0;
    }
```

Thanks. :)

**Comment by andrewbird** [comment]
Mmm I think that's because redirector uses int2f/1203 function to find data segment. My fault I know, but without it we have to chase the moving of lol location? If we didn't need lol for lfn, if wouldn't be a problem.

**Comment by andrewbird** [comment]
Just thinking aloud here, so the only DOS with the problem is fdpp, and you control that so how about you define a new int2f/12xx function that the redirector can ask where the various dos structures are instead of assuming that dos data segment is constant for them all?

**Comment by stsp** [comment]
Why would you use 1203 instead of
proper get lol (52) and get dta (5d06)?
Quite a bad choice.

**Comment by stsp** [comment]
> define a new

Use old ones. :)

**Comment by stsp** [comment]
> define a new

Use old ones. :)

**Comment by andrewbird** [comment]
Or even better, a change to the fdpp interface so that fdpp can tell dosemu when they change?

**Comment by stsp** [comment]
> Or even better, a change to the fdpp interface so that fdpp can tell dosemu when they change?

You did that for edr-dos, not fdpp.
And the bug is simple: you used the wrong func.

**Comment by andrewbird** [comment]
Calling int21 from inside the redirector is reentrant, that's why there are duplicates of int21 functions at int2f/12.

**Comment by stsp** [comment]
We have `enable_redirect()` hook that
is called at later stage. You need to call
DOS_SUBHELPER_MFS_REDIR_INIT
from there again, to re-initialize pointers.
Would you like to do that?

**Comment by andrewbird** [comment]
Not really, I thought I'd killed pointer chasing for good! Can't we think of some other way of removing the need for lol? It's almost gone from lfn.c, init.c only initialises it, dosdebug use is optional, mfs is only really concerned with updating it for use by lfn.c.

**Comment by andrewbird** [comment]
I think killing lol use is certainly possible and hence the requirement for seg(lol) == seg(sda) can be relaxed, and your tweak to int21/52 can be used. Killing sda use in lfn.c would be far more problematic, but that won't matter unless you intend to move sda from dos data segment?

**Comment by stsp** [comment]
Killing lol is fine, but I think pointer reinit
should be moved regardless, for sda.
We re-initialize the redirector after config.sys
anyway because cds move. So I don't
understand a need for something special.

**Comment by andrewbird** [comment]
There's one thing stopping `lol` removal it's `get_nuldev()` which is used by `is_dos_device()` which is used by loads of stuff! We could replace direct calls in the redirector itself by `int2f/1223`, but those in lfn.c (and via truename etc) that presumably need all the unix path checking won't be so easy. Speaking of `is_dos_device()` doing unix path checking, this use of it in mscdex to confirm that they actually found a driver seems dubious:
https://github.com/dosemu2/dosemu2/blob/a6845779882bf260a4cd8b31db337ad5d1e6b3f4/src/dosext/mfs/mscdex.c#L302-L315
From what I understand, `is_dos_device()` returns true not if the name is a loaded device driver but if it's name could be a reserved device name.

I think you'd better do your pointer magic, as it seems more achievable in the short term.

**Comment by andrewbird** [comment]
I heavily edited my last post, I had made a mistake about where the path checking was.
