### ISSUE TITLE
No edit.exe

### ISSUE THREAD

**Issue by Hordeking** [dosemu2/fdpp#163]
Perhaps I'm missing some things, but where exactly are the standard dos utils like edit.exe and so on and so forth? Do they have different names?

**Comment by stsp** [comment]
fdpp is just a DOS core.
It doesn't include any utils.
You are probably trying it with
dosemu2, in which case its a
dosemu2's question.

Anyway, in dosemu2 we were supposed
to install the freedos utils but that project
seems to be stalled.
@jschwartzenberg Are there any hopes
for you to do further work on your download
scripts? If not, please tell me so and I will
think what to do next.

**Comment by jschwartzenberg** [comment]
Yeah unfortunately I did not manage to spend time on this recently. I had split some things out previously and created initial installation files using `xmake` as the build tool. I just pushed what I had on my system to two private repos the dosemu2 organization. Maybe you could take a look and see what next steps would make sense in your eyes.

If it all works correctly, `install-freedos` should install on top of `dosemu2` and `install-otherdos` should install on top of `dosemu2`+`install-freedos`.

I'm planning to take off some weeks soon and I might be able to write improvements too.

**Comment by stsp** [comment]
Can you please make these repositories
not so private, so that they allow anonymous
clones?

**Comment by jschwartzenberg** [comment]
Yeah, sure, I assumed you could do that too and I didn't want to put anything public in the dosemu2 organization without your blessing :)

**Comment by stsp** [comment]
If github allows doing that w/o my
"blessing", then it is how it should be. :)
Why do you need xmake there?
Maybe instead you can add debian
rules and rpkg file?

**Comment by jschwartzenberg** [comment]
I had never heard of rpkg, but it seems interesting. I think it should be possible to add both yep. I used `xmake` as a replacement for `make` to do the installation. `xmake install` should do the trick.

**Comment by stsp** [comment]
> I had never heard of rpkg

See dosemu2.spec.rpkg, its mostly the
same as an rpm spec.

> for make to do the installation. xmake install should do the trick.

Perhaps its not needed.
In packaged version the install is
not needed, and in source version
perhaps we can set the path to them
via configure of dosemu2, similar to
what we do for dosemu-freedos.bin.
Then "make install" of dosemu2 will
do the trick.

**Comment by jschwartzenberg** [comment]
Sounds good! I hope I can do this soon, at least for one of the two. I forgot to make the `msexpand` repo public, I made it public as well now.

**Comment by stsp** [comment]
Why dosemu-installfreedos is not in
install-otherdos repo?
I think we wanted to special-case only
the freedos user-space.

**Comment by stsp** [comment]
I added --with-contribdir which allows to
install your scripts.
Does this help?

**Comment by stsp** [comment]
Though I am not sure if it was the right
thing to do, as it doesn't help you to build
the package. You still need your own install
of you would build-require dosemu for that. :)
So moved to a separate branch.

**Comment by stsp** [comment]
Package install-freedos is now in our repos.
Please test and tell us how it goes.
