### ISSUE TITLE
fedora copr packages broken, "failed to open [junk]"

### ISSUE THREAD

**Issue by taviso** [dosemu2/fdpp#170]
**Describe the bug**

The fedora copr packages are broken again and don't boot, the error is:

```
$ dosemu
failed to open  �S��U
ERROR: FDPP boot failed
```

**A regression?**

Yes, these two work:

fdpp-0.0.git.1151.0fb0dcb-1.fc32.x86_64
dosemu2-0.0.git.2339.260ff21f-1.fc32.x86_64

These two don't boot:

dosemu2-0.0.git.2343.b9ff472d-1.fc32.x86_64
fdpp-0.0.git.1159.2598ffc-1.fc32.x86_64

**Comment by taviso** [comment]
Thanks Stas!

**Comment by taviso** [comment]
FYI, it still doesn't boot, but it doesn't crash now.

```
$ dosemu
failed to open /usr/lib64/fdpp/fdppkrnl.elf
ERROR: FDPP boot failed
```

**Comment by stsp** [comment]
So you need to upgrade fdpp and make
sure `/usr/lib64/fdpp/fdppkrnl.elf` is there.

**Comment by taviso** [comment]
Yes, it doesn't work.

```
$ rpm -q fdpp
fdpp-0.0.git.1162.0fc6321-1.fc32.x86_64
$ file /usr/lib64/fdpp/fdppkrnl.elf 
/usr/lib64/fdpp/fdppkrnl.elf: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), statically linked, BuildID[sha1]=f4edc6101d3b3f1eb4546ea391b04481cd41a413, stripped
```

**Comment by taviso** [comment]
There's nothing very helpful in the log, just this:

``Warning: WARNING: image filedesc not open``

Perhaps related to the recent terminal stderr closing change?

**Comment by stsp** [comment]
No, rpmbuild just strips it, even though
I removed the exec attr to hide it from
stripping.
Will figure that out later.

**Comment by stsp** [comment]
Should now be fixed.
