### ISSUE TITLE
failed to open /usr/share/fdpp/fdppkrnl.elf

### ISSUE THREAD

**Issue by magiblot** [dosemu2/fdpp#181]
I get this error when running dosemu2 after updating to the latest fdpp (b219d38168304c0c9ffa0f09f24bf5a932c3b085) on ArchLinux (via the [fdpp package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=fdpp&id=dd78bc2f1555b3cce4241e58f7d219eae3199e94) from AUR in `-git` mode).

I'm unable to figure out whether this is a problem with my setup or an issue in fdpp.

I'm using the following software versions:

```
linux 5.13.12 x86_64
clang 12.0.1
nasm 2.15.05
ldd (GNU libc) 2.33
```

Here are the files in /usr/share/fdpp: [fdpp.tar.gz](https://github.com/dosemu2/fdpp/files/7040441/fdpp.tar.gz)

**Comment by stsp** [comment]
Its stripped and therefore cannot
be used. This is a packaging problem,
please report upstream.

**Comment by magiblot** [comment]
Thanks! That was the issue.

**Comment by stsp** [comment]
Did they fix it?

**Comment by magiblot** [comment]
Not yet, but I manually tweaked the PKGBUILD file to disable automatic stripping (`options+=(!strip)`). Although it applies to the whole package instead of just specific files.

**Comment by stsp** [comment]
We intentionally remove
the +x attr from that file.
Automatic packaging tools
never strip binaries w/o +x
(deb, rpm). So the tools in
archlinux might be buggy.

**Comment by stsp** [comment]
If you can't fix tools, you
can use the --strip-debug
option. It will still strip the
rest of the package, and
will not corrupt fdpp.

**Comment by magiblot** [comment]
> We intentionally remove
> the +x attr from that file.
> Automatic packaging tools
> never strip binaries w/o +x
> (deb, rpm). So the tools in
> archlinux might be buggy.

Thanks for the info. This is worth asking to the makepkg developers.
