### ISSUE TITLE
audit _LOWTEXT uses

### ISSUE THREAD

**Issue by stsp** [dosemu2/fdpp#187]
d4ae636 removed _TEXT_DGROUP.
Not sure if that's right or not.
b421fc0 moved intvec_table, that one
should be OK.
There are 3 more _LOWTEXT usages
in the code, that I have no idea about.
Ideally all of them should be removed
because _LOWTEXT is not low at all
in fdpp.

**Comment by stsp** [comment]
Tests seem to fail because of
some ia16-gcc problem:
https://github.com/dosemu2/dosemu2/runs/4195218622?check_suite_focus=true
What can that be?

**Comment by andrewbird** [comment]
> Tests seem to fail because of
some ia16-gcc problem:
https://github.com/dosemu2/dosemu2/runs/4195218622?check_suite_focus=true
What can that be?

Tagging @tkchia here as I'm sure he'll be able to figure out what's happening.
