### ISSUE TITLE
create dev package

### ISSUE THREAD

**Issue by stsp** [dosemu2/fdpp#188]
To ease the integration to distros,
the -dev package may be needed.
But last time I tried that a few years
ago, lintian was beating me up to
rename the package to libfdpp0
or alike, Which is no go.
But I need to try again as my
memory can be wrong on that.

**Comment by andrewbird** [comment]
Perhaps search the Debian repos and see if there are any other -dev packages named as you wish?

**Comment by stsp** [comment]
I guess @skitt can tell us if
needed to do that, and if so - how.
