### ISSUE TITLE
Cannot DIR with netware vlm client

### ISSUE THREAD

**Issue by bpranoto** [dosemu2/fdpp#197]
I tried to install netware vlm dos client on dosemu2+fdpp+comcom32 system.

Loading the vlm client (lsl and vlm) is good, it can see and attach and even log in to the netware server.

However, once we access the mapped drive with `DIR F:` (which list nothing)  dosemu can only list he first file on the local drives. DIR D: now only shows the first file (FDAUTOEM.BAT).  `DIR` on mapped network drives (F:, Z:) shows nothing. 

Despite the problem, dosemu doesn't crash, I can even call EXITEMU to exit. 

Attached is the boot log with -DD9

[boot.log](https://github.com/dosemu2/fdpp/files/8601509/boot.log)

**Comment by andrewbird** [comment]
Hi there,
  I think you'll need to rerun your test with the logging for MFS turned on i.e. `-DD9d` otherwise we won't be able to see if the filesystem calls are being handled by Netware or our redirector.
  Also
 - what is the output of the lredir command?
 - what is the output of the Netware command to list mapped drives?

**Comment by bpranoto** [comment]
Output of lredir:

![image](https://user-images.githubusercontent.com/7417263/166214626-0c6dcf57-33a9-43e3-acba-4652878489e7.png)

The netware command MAP.EXE resides in netware SYS:PUBLIC directory, so it can't be executed because DOSEMU is unable to see it.

Attached is the log file with -DD9d
[boot.log](https://github.com/dosemu2/fdpp/files/8602039/boot.log)

**Comment by andrewbird** [comment]
> The netware command MAP.EXE resides in netware SYS:PUBLIC directory, so it can't be executed because DOSEMU is unable to see it.

Is SYS:PUBLIC mapped itself? Can you execute it by full path e.g. `F:\map.exe`? I'm aiming to see whether just findfile/next is broken or the whole interaction between Netware and our redirector.

**Comment by bpranoto** [comment]
When I was logged in, the mapping commands in the login script is executed
![image](https://user-images.githubusercontent.com/7417263/166219980-438aa21e-da56-467d-8f15-01ade93b3b8c.png)

But, as you can see in the screenshot, I cannot execute the map.exe by its full path.

**Comment by andrewbird** [comment]
I think I'm going to have to try to recreate your setup here. What versions of Netware server and client are you running?

**Comment by andrewbird** [comment]
BTW I think I setup Netware only once 30 years ago, so it might be a challenge!

**Comment by bpranoto** [comment]
Netware server version 6.5 sp8 (latest version before discontinuation)
vlm v1,21

Other problem is current linux kernel drops ipx and ncpfs support, we have to install the kernel modules by ourself.

I think it will be easier if I give you ssh access to my computer? I just install the computer because it is an unused old computer. Please give me your email address.

**Comment by bpranoto** [comment]
you can contact me at bpranoto@gmail.com

**Comment by andrewbird** [comment]
I forgot to ask, is this a regression or has it never worked?

**Comment by bpranoto** [comment]
It is the first time I try in dosemu2/fdpp.

**Comment by bpranoto** [comment]
it works in opendos

**Comment by stsp** [comment]
Try freecom instead of comcom32.
If that fails too, try freedos.
And in case of fdpp please add
the `f` letter to the log flags.

**Comment by andrewbird** [comment]
> it works in opendos

Interesting, that's unexpected to me.

@stsp , he's provided me with ssh now and I can confirm it's the same with freecom. I noticed from one of the logs he posted that something obtained LOL and SDA, so there might be some direct poking of those structures going on.
I just tried Freedos 1.2 kernel + freecom and that works okay to dir c: (mfs) and dir z: (netware).

**Comment by stsp** [comment]
Cool, thanks for info.
If it goes for lol, try $_dos_up=(off)
to see if maybe it doesnt like lol in umb.

**Comment by andrewbird** [comment]
> If it goes for lol, try $_dos_up=(off)

No, unfortunately it didn't help.

Here are the logs with `-f` from the previous run (with default dos_up) 
[t1.zip](https://github.com/dosemu2/fdpp/files/8603817/t1.zip)

**Comment by andrewbird** [comment]
This FDPP debugging is probably beyond me, I was expecting an MFS problem. @bpranoto if @stsp wants to take over, will you extend the login details to him please?

**Comment by stsp** [comment]
Works fine with freedos.
So the interesting thing is
that vlm changes int2f/111ch
call (findnext) with 110ch
call under fdpp...

**Comment by stsp** [comment]
Should now be fixed.

**Comment by stsp** [comment]
Andrew, would you like to add
test about SS=DOS_DS (and
maybe some other things you
can think of) on the appropriate
redirector calls?

**Comment by stsp** [comment]
I wonder if other things, like
SFT pointers, should also be
relative to DOS_DS? Although
I haven't seen this ever documented
that way.

**Comment by andrewbird** [comment]
> Andrew, would you like to add
test about SS=DOS_DS (and
maybe some other things you
can think of) on the appropriate
redirector calls?

Do you have an idea on how to implement such a test? My only idea is that maybe I could sample dosemu's log file, but I think I'll have difficulty associating the section of log with the test call.
