### ISSUE TITLE
FCB (int 21h func 29h): should keep parsing name even if drive letter invalid

### ISSUE THREAD

**Issue by tkchia** [dosemu2/fdpp#200]
On both MS-DOS 2.11 and MS-DOS 5.0, the "parse filename to FCB" syscall (`int 0x21`, function `0x29`), when it encounters an invalid drive letter, will still continue parsing the file name, and return with `al` = `0xff` _and_ `ds:si` pointing after the parsed file name.

E.g. given an input like `z:foo.bar,baz` — assuming `z` is not a valid drive letter — the syscall will return `al` = `0xff` and `ds:si` pointing at the comma.

FreeDOS++ should probably do likewise.  I have already submitted a proposed patch to the upstream FreeDOS kernel project, at https://github.com/FDOS/kernel/pull/82 .

(**Edit:** I also submitted another patch upstream at https://github.com/FDOS/kernel/pull/83 which fixes a problem in my earlier patch.)

Thank you!

**Comment by stsp** [comment]
Andrew, am I remember correctly
that we already did that?

**Comment by andrewbird** [comment]
Your memory must be better than mine, I have no recollection of this topic. Perhaps I should write a test to see what the other DOSes do.

**Comment by stsp** [comment]
But I suppose @tkchia already has such
test?

**Comment by tkchia** [comment]
Hello @stsp, hello @andrewbird,

The test code for this particular behaviour for `int 0x21`, `ah` = `0x29`, is now in my `libi86` master branch &mdash; though the test is disabled for now.  Let me know if you would like me to enable the test.  Thank you!

**Comment by stsp** [comment]
Ping.
Andrew, have you looked at a test?

**Comment by stsp** [comment]
@tkchia maybe you can just
check fdpp yourself and submit
a patch if needed?

**Comment by tkchia** [comment]
Hello @stsp,

> @tkchia maybe you can just check fdpp yourself and submit a patch if needed?

Hmm... let me look into doing that.  Thank you!
