### ISSUE TITLE
FDPP panic with HDIMAGE that has multiple partitions

### ISSUE THREAD

**Issue by andrewbird** [dosemu2/fdpp#203]
I created a multi partition hdimage to test partition detection etc. With the following config I get a panic from FDPP, however with FreeDOS 1.2 the boot is successful.
```conf
$_force_fs_redirect = (off)
$_hdimage = "dXXXXs/c:hdtype1 multimbr.img +1"
$_floppy_a = ""
```
~~~
FDPP kernel 1.6 [GIT: 1.6-29-ga93924a6] (compiled Sep  5 2022)
Kernel compatibility 7.10 - clang - FAT32 support
 
Written by Stas Sergeev, FDPP project.
Based on FreeDOS sources (C) Pasquale J. Villani and The FreeDOS Project.
 
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
 
C: HD1, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=    10 MB
D: HD2, Pri[ 1], CHS=    0-32-33, start=     1 MB, size=    10 MB
E: HD3, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
F: HD4, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
G: HD5, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
H: HD2, Pri[ 2], CHS=    1-102-38, start=    11 MB, size=    20 MB
I: HD2, Pri[ 3], CHS=    3-242-48, start=    31 MB, size=    35 MB
J: HD2, Pri[ 4], CHS=    8-105-34, start=    66 MB, size=    34 MB
PANIC: Dyn 7823
Press any key to exit.
~~~
[multimbr.zip](https://github.com/dosemu2/fdpp/files/9535242/multimbr.zip)

**Comment by stsp** [comment]
This means OOM.
Please try this:
```
diff --git a/src/plugin/fdpp/hooks.c b/src/plugin/fdpp/hooks.c
index 5cfa37816..070c80bdc 100644
--- a/src/plugin/fdpp/hooks.c
+++ b/src/plugin/fdpp/hooks.c
@@ -111,7 +111,7 @@ static int fdpp_pre_boot(unsigned char *boot_sec)
     if (!hndl)
         return -1;
     if (config.dos_up) {
-        heap_sz = 1024 * 3;
+        heap_sz = 1024 * 4;
```

**Comment by andrewbird** [comment]
Thank you, that works just fine.

**Comment by stsp** [comment]
Applied but unfortunately @bolle732
will report the OOM again.
Needs a reproducer.

**Comment by andrewbird** [comment]
Looks like we are seeing in the tests now.
~~~
C:\>lredir

ERROR: SMALLOC: Out Of Memory on alloc, requested=1024
Total size: 16384
Available space: 459 (15925 used)
Largest free area: 459
Memory pool dump:
	area: 512 bytes, used
	area: 15408 bytes, used
	area: 5 bytes, used
	area: 459 bytes, free

ERROR: lowmem_heap: OOM, size=1024
~~~

**Comment by stsp** [comment]
Ok, LFNs...
I think @bolle732 uses freecom.
Anyway, in that case I enlarged
dosemu2 heap so we'd have 1Kb
fewer for UMBs.

**Comment by bolle732** [comment]
I'm using pure DOSEmu2 with FDPP und COMCOM32 ;-)

And yes, I'm a user of LFN. PC/GEOS still is starting fine on latest devel.

So, changing `heap_seg` to `0x50` in `src/plugin/fdpp/hooks.c`won't work anymore? I suppose that this is an effect of the latest patch. There is now 1kB more conventional memory used (2352B vs 1328B).

**Comment by bolle732** [comment]
As you wrote in the commit message...

**Comment by stsp** [comment]
> So, changing heap_seg to 0x50 in src/plugin/fdpp/hooks.cwon't work anymore?

That should still work.

> There is now 1kB more conventional memory used (2352B vs 1328B)

No, shouldn't be related to that
patch. It only shrinks available
UMBs by 1K (from 156K to 155K).

**Comment by stsp** [comment]
Btw I wonder how does freedos
handle that and the loadfix problem.
I think freedos has a hack to disable
A20 every time you leave the kernel.
But how does that work with 4a02?

Andrew, could you please add to the
HMA tests a check to make sure the
space allocated with 4a02 actually works?
By writing there and making sure it
was actually written to HMA, not wrapped
to a lowmem.

**Comment by stsp** [comment]
Maybe we'll get freedos busted
with such test.

**Comment by andrewbird** [comment]
> By writing there and making sure it
was actually written to HMA, not wrapped
to a lowmem.

So I might need a hint here. If I get a block at ffff:xxxx and write to it, how can I be sure that when I read it back in DOS that I'm not subject to the same wrapping (if any) that occurred during write?

**Comment by andrewbird** [comment]
Or perhaps I just read from the location in lowmem that it would have wrapped to and check it's not there?

**Comment by stsp** [comment]
Exactly, check its not there.

**Comment by ecm-pushbx** [comment]
> Btw I wonder how does freedos handle that and the loadfix problem. I think freedos has a hack to disable A20 every time you leave the kernel. But how does that work with 4a02?
> 
> Andrew, could you please add to the HMA tests a check to make sure the space allocated with 4a02 actually works? By writing there and making sure it was actually written to HMA, not wrapped to a lowmem.

I believe that [the function DisableA20](https://github.com/FDOS/kernel/blob/7149a8efe49f9d33dbabfd280517c6da06086a73/kernel/kernel.asm#L1197) is the only place where the kernel actually disables A20. This is called [once in inithma.c](https://github.com/FDOS/kernel/blob/7149a8efe49f9d33dbabfd280517c6da06086a73/kernel/inithma.c#L137) to test whether the kernel can disable A20, and [in kernel.asm](https://github.com/FDOS/kernel/blob/7149a8efe49f9d33dbabfd280517c6da06086a73/kernel/kernel.asm#L1243) function ExecUserDisableA20. This is in turn only called [from procsupt.asm](https://github.com/FDOS/kernel/blob/7149a8efe49f9d33dbabfd280517c6da06086a73/kernel/procsupt.asm#L45) function exec_user.

And that one is called twice, both in task.c, [once in process termination](https://github.com/FDOS/kernel/blob/7149a8efe49f9d33dbabfd280517c6da06086a73/kernel/task.c#L603) (but this sets the `disable_a20` parameter to zero) and the other time [in process creation](https://github.com/FDOS/kernel/blob/7149a8efe49f9d33dbabfd280517c6da06086a73/kernel/task.c#L380) where the parameter is actually set to one. So the kernel only disables A20 when creating a process, and even then it appears only with function 21.4B00 (not with debugger load-and-return, interestingly enough).

All interrupt 2Fh calls that end up in the kernel also enable the HMA when the kernel is relocated to the HMA. And none of them use DisableA20, so it will always stay enabled afterwards.

**Comment by andrewbird** [comment]
Having some brain ache here. If the returned address is FFFF:0010 what would its wrapped address be if it were occurring?

**Comment by ecm-pushbx** [comment]
> Having some brain ache here. If the returned address is FFFF:0010 what would its wrapped address be if it were occurring?

Segment FFFFh = Linear F_FFF0h. Segmented FFFFh:0010h = Linear F_FFF0h + 10h = 10_0000h.

**Comment by stsp** [comment]
Wrapped address = linear&0x100000

**Comment by stsp** [comment]
Edited the above commend for
forgotten -1

**Comment by ecm-pushbx** [comment]
Equivalently, wrapped linear = full linear & ~10_0000h. (Mask off A20 bit, where 20 = 21st address line.)

**Comment by stsp** [comment]
Your formula is "better" of some
sort, eg it will work even when
higher bits are active (eg in unreal
mode).

**Comment by andrewbird** [comment]
Cool, thanks.

**Comment by stsp** [comment]
Well, in kernel.asm I can see
the calls to `call near forceEnableA20`
but not corresponding disables.
So I guess my recollections were
wrong and there is no such problem
in freedos. Still wonder why to call
this enable() per every DOS call...

**Comment by ecm-pushbx** [comment]
> Still wonder why to call this enable() per every DOS call...

It's valid for the user process to disable A20 by itself. Every entrypoint has to insure it is on again before jumping into the HMA DOSCODE.

**Comment by stsp** [comment]
Good that I abandoned HMA. :)
Besides the above discrepancy,
there is also now no longer those
"packed file is corrupt" with fdpp.

**Comment by andrewbird** [comment]
Is there any easy way I can programmatically turn on wrapping to test my test code?

**Comment by stsp** [comment]
Disable a20 with int15/2400h?

**Comment by stsp** [comment]
Perhaps you can leave that in
a test. I.e. test things with a20
disabled too. But you probably
need to preserve and later
restore the area you corrupted
in lowmem.

**Comment by andrewbird** [comment]
Cool, thanks, that worked fine (I guess I was lucky with the memory corruption!).

**Comment by andrewbird** [comment]
I added a test, but it may need some debugging. Seems to be fine on FDPP, FreeDOS 1.2 is skipped, DR-DOS hangs and MSDOS doesn't wrap when it should. I have to go out now for a while, back later. See https://github.com/andrewbird/dosemu2/tree/t28

**Comment by stsp** [comment]
You need to save before the
first write. We test for misbehavior
so you can't assume nothing gets
corrupted.

**Comment by stsp** [comment]
Also even though RBIL doesn't
document the failure, I believe
you need to set CF before 4a02
and check if its still set after a
call.
Also please do `union REGS r = {};`
to not leave garbage in regs.

**Comment by andrewbird** [comment]
> You need to save before the
first write. 

Yes, unfortunately that doesn't fix it for DR-DOS. Is there any reason why I can't change my method to read HMA, then read wrapped address in conventional memory, and then do the compare to avoid the corruption? I guess the risk is that both regions might be zeroed, but I could check for that.

**Comment by stsp** [comment]
You can back up lowmem in a
buffer. Then write to HMA and
compare lowmem with backup.
If they match then HMA write was
OK. If not - you can restore lowmem.
I think that algo is quite optimized. :)

**Comment by andrewbird** [comment]
> You can back up lowmem in a
buffer. Then write to HMA and
compare lowmem with its backup.
If they match then HMA write was
OK. If not - you can restore lowmem.

Yes that's what I'm doing for the first part and works okay. For the second I purposefully enable the wraparound and do much the same, except that in the normal case the lowmem gets corrupted and DR-DOS freaks out before I can restore it.

Just altering the test slightly so at least I can test on FreeDOS 1.2.

**Comment by stsp** [comment]
> Yes that's what I'm doing for the first part

No, its different.
See carefully:
1. You backup lowmem
2. You write to HMA
3. You check lowmem against it backup
This guarantees that you have
a backup even on the first test,
which may also corrupt something
otherwise.

> DR-DOS freaks out before I can restore it.

Disable interrupts.

**Comment by andrewbird** [comment]
> No, its different.

Sorry I hadn't pushed after your suggestions.

>> DR-DOS freaks out before I can restore it.

> Disable interrupts.

Still seeing lots of `SIGILL while in vm86(): fef2:3f91` in the log. Disabling kvm shows
~~~
!!! Illegal op ff ff ff                                                         
SIGILL while in vm86(): fef2:41bd
~~~

Latest code at https://github.com/andrewbird/dosemu2/tree/t28

**Comment by stsp** [comment]
You need to disable interrupts
before disabling a20. Possibly
dr-dos doesn't have a rescue
code to forcibly re-enable it.
You'd also need to defer any
DOS calls (like printf() and alike)
until after you re-enable a20
and interrupts.

**Comment by andrewbird** [comment]
> You need to disable interrupts
before disabling a20.

That fixed the problem for MS-DOS 6.22. Both FreeDOS 1.2 and DR-DOS 7.01 stop outputting in the same place i.e.
~~~
C:\>c:\hmaalloc
INFO: HMA size returned 48
INFO: HMA block allocated at FFFF:AB28
INFO: A20 is initially enabled
INFO: Wrapping is not evident
~~~

**Comment by stsp** [comment]
You need to re-enable a20
before enabling interrupts.

**Comment by andrewbird** [comment]
> You need to re-enable a20
before enabling interrupts.

Yep that seems to have fixed it, thanks.
