### ISSUE TITLE
Cannot install FDPP on Alpine Linux

### ISSUE THREAD

**Issue by hjlinq** [dosemu2/fdpp#207]
![image](https://user-images.githubusercontent.com/68657588/200402211-26fc7cea-9388-4138-a3f8-9bc57197d726.png)

To reproduce this error:

1: install Alpine Linux in a VM (I used alpine-extended-3.16.2-x86_64.iso)
2: apk add git
3: git clone https://github.com/dosemu2/fdpp.git
4: apk add bash clang nasm elfutils-dev flex bison autoconf
5: cd fdpp
6: ./configure
7: make

Thank you.

**Comment by stsp** [comment]
You need to install libstdc++.

**Comment by stsp** [comment]
libstdc++-dev
