### ISSUE TITLE
Building FDPP on Aarch64

### ISSUE THREAD

**Issue by Nobody-Special** [dosemu2/fdpp#227]
While building FDPP on Aarch64, Android 13 with packages from Termux, I had to make the following changes:

```diff
# No Aarch64 target seems to be able to cross-link with elf32 (I might be wrong). See note on the bottom of 3.1.2 section under provided URL link.
# https://github.com/ARM-software/abi-aa/blob/844a79fd4c77252a11342709e3b27b2c9f590cf1/aaelf64/aaelf64.rst#bit-pointers-elf32-beta
# Line 40
-NASMFLAGS += -i$(SRC)/ -f elf32
+NASMFLAGS += -i$(SRC)/ -f elf64

# LD can figure out the format of object file on its own
# Line 76
-       $(CROSS_LD) -melf_i386 -static -Map=$(TARGET).map -o $@ \
+       $(CROSS_LD) -static -Map=$(TARGET).map -o $@ \
                $(^:%.ld=-T%.ld) --defsym=DOS_PSP=0x60
        chmod -x $@

# Line 81
-       $(CROSS_LD) -melf_i386 -static -o $@ \
+      $(CROSS_LD) -static -o $@ \
                $(^:%.ld=-T%.ld) --defsym=DOS_PSP=0
        chmod -x $@
```

Unfortunately I have hit another road block:

```
lex /data/data/com.termux/files/home/Projects/fdpp/fdpp/parsers/thunk_gen.l
make[2]: lex: No such file or directory
make[2]: *** [makefile:24: lex.yy.c] Error 127
make[2]: Leaving directory '/data/data/com.termux/files/home/Projects/fdpp/fdpp/parsers'
make[1]: *** [makefile:241: parsers/thunk_gen] Error 2
make[1]: Leaving directory '/data/data/com.termux/files/home/Projects/fdpp/fdpp'
make: *** [makefile:13: all] Error 2
```

And have no idea what to do about it. Any suggestions?

**Comment by stsp** [comment]
Try `export LEX=flex` before running
`make`. Maybe you have flex installed.
If not - install.

I have no idea why you need to change
nasm flags. We have aarch64 build on
LP, so the fewer changes you do, the
more chances to succeed.

**Comment by stsp** [comment]
Yes, this is informational-only msg.
Please run `file *.elf` to check the arch
of the resulting file after you removed
melf_i386.

**Comment by stsp** [comment]
> Clang constantly is screaming about macro redefinitions

Which ones?

**Comment by Nobody-Special** [comment]
`file ./fdpp/*.elf`:

```
./fdpp/fdppkrnl.32.10.elf: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), statically linked, not stripped
```

>> Clang constantly is screaming about macro redefinitions
>
> Which ones?

- O_SYNC,
- O_LARGEFILE,
- O_CREATE O_TRUNC,
- O_AACMODE,
- O_RDWR,
- O_RDONLY,
- O_WRONLY

Excerpt:
```
In file included from /data/data/com.termux/files/home/Projects/fdpp/kernel/globals.h:51:
/data/data/com.termux/files/home/Projects/fdpp/fdpp/../hdr/file.h:53:9:
warning: 'O_RDONLY' macro redefined [-Wmacro-redefined]
#define O_RDONLY        0x0000                                     ^
/data/data/com.termux/files/usr/include/asm-generic/fcntl.h:25:9: note: previous definition is here
#define O_RDONLY 00000000
```

**Comment by stsp** [comment]
So what CROSS_LD was that?
lld?

**Comment by Nobody-Special** [comment]
Yes. LLD 16.0.6

**Comment by Nobody-Special** [comment]
Mea culpa. By trying to edit a comment, I've deleted it by accident. Do you want me to write down the list of macro redefinitions once again?

**Comment by stsp** [comment]
I've got your comment via email.
Does lld list the supported targets and
what option should be used?

**Comment by Nobody-Special** [comment]
I've played a little bit with `$CROSS_LD`.

Under Gnu ld (GNU Binutils 2.40) compilation fails:

```
ld -melf_i386 -static -Map=fdppkrnl.32.10.map -o fdppkrnl.32.10.elf \
-T/data/data/com.termux/files/home/Projects/fdpp/fdpp/kernel.ld kernel.o entry.o io.o console.o serial.o printer.o execrh.o nlssupt.o procsupt.o dosidle.o int2f.o nls_hc.o intr.o irqstack.o cpu.o plt.o cdata.o floppy.o rdpcclk.o wrpcclk.o wratclk.o --defsym=DOS_PSP=0x60                                ld:
unrecognised emulation mode: elf_i386
Supported emulations:
aarch64linux,
aarch64elf,
aarch64elf32,
aarch64elf32b,
aarch64elfb,
armelf,
armelfb,
aarch64linuxb,
aarch64linux32,
aarch64linux32b,
armelfb_linux_eabi,
armelf_linux_eabi

make[1]: *** [makefile:76: fdppkrnl.32.10.elf] Error 1
make[1]: Leaving directory '/data/data/com.termux/files/home/Projects/fdpp/fdpp'                                            make: *** [makefile:13: all] Error 2
```

While under ld.lld (clang/llvm) compiles without truble with no modifications to makefile.

**Comment by stsp** [comment]
Yes, that's the point.
cross-ld should be lld.
How it happened to be something else?

**Comment by stsp** [comment]
Macros should now be fixed.

**Comment by Nobody-Special** [comment]
I wish I would know. I've tried unsetting `$CROSS_LD` and reinstalling `binutils`, as well as looking for exports... but to no avail.

I think this issue can be closed now. Unless you want it to be mentioned in #225 as I think it might be a road blocker.

**Comment by stsp** [comment]
But lld is not the part of binutils, that's
the problem.
What road blocker?

**Comment by Nobody-Special** [comment]
> But lld is not the part of binutils, that's the problem.

But `ld` is. In short, i've tried reinstalling binutils to see if in Termux it sets `$CROSS_LD` to `ld`.

------

> What raod blocker?

In my understanding if you want to migrate FDPP to GCC, you don't want a dependency on llvm through lld and instead use ld.

I'm not sure if this logic is sound, so please correct me if I'm wrong.

**Comment by Nobody-Special** [comment]
Ok. Thanks for clarification :)
