### ISSUE TITLE
fdpp install doesn't produce fdppkrnl.elf

### ISSUE THREAD

**Issue by severach** [dosemu2/fdpp#229]
fdpp has been improved with versioned libraries and executables. The unversioned lib is produced correctly. However we need symlinks for `fdppkrnl.elf` and `fdppkrnl.map`.

**Comment by stsp** [comment]
For what?

**Comment by severach** [comment]
This is all that bd42012 fdpp make install produces. Dosemu default install will not boot to fdpp.

````
-rw-r--r-- root/root     38204 2023-08-04 12:17 usr/share/fdpp/fdppkrnl.32.10.elf
-rw-r--r-- root/root     74560 2023-08-04 12:17 usr/share/fdpp/fdppkrnl.32.10.map
````

I create these symlinks to mimic the filenames made by c9eb2df and Dosemu boots to fdpp.

````
lrwxrwxrwx root/root         0 2023-08-04 12:17 usr/share/fdpp/fdppkrnl.elf -> fdppkrnl.32.10.elf
lrwxrwxrwx root/root         0 2023-08-04 12:17 usr/share/fdpp/fdppkrnl.map -> fdppkrnl.32.10.map
````

**Comment by stsp** [comment]
> Dosemu default install will not boot to fdpp.

Please, that's nonsense.
It works on our CI and for everyone else too.
