### ISSUE TITLE
Error posted about redundant conversion

### ISSUE THREAD

**Issue by andrewbird** [dosemu2/fdpp#230]
**Describe the bug**
Error posted about redundant conversion

**To Reproduce**
~~~
ajb@calypso:~/Desktop$ dosemu
ERROR: MIDI: unsupported synth mode mt32
ERROR: redundant conversion for 0x7fce856fad21

ERROR: Please update dosemu from git, compile it with debug
info and make a bug report with the content of ~/.dosemu/boot.log at
https://github.com/dosemu2/dosemu2/issues
Please provide any additional info you can, like the test-cases,
URLs and all the rest that fits.
~~~

**Attach program/game binaries or provide an URL**
-

**Attach the log**
[t1.zip](https://github.com/dosemu2/dosemu2/files/12570695/t1.zip)

**A regression?**
yes

**Additional info**
I don't seem to be able to select the text in the window any more with shift-leftmb, but here I am running FDPP with Freecom.

**Comment by stsp** [comment]
Should now be fixed, please check.

**Comment by andrewbird** [comment]
Yes is fine now, thanks.
