### ISSUE TITLE
tests are failing again

### ISSUE THREAD

**Issue by stsp** [dosemu2/fdpp#236]
Hi Andrew, could you please take
a look at what's going on here:
https://github.com/dosemu2/fdpp/actions/runs/6890748254/job/18745222483
Can't reproduce locally:
```
$ test/test_dos.py PPDOSGITTestCase.test_libi86_item_003
Test PP-DOS-GIT  libi86 item   3 dosemu                                          ... ok (  3.12s)

----------------------------------------------------------------------
Ran 1 test in 3.122s

OK
```

Not sure what happened actually...
Spent the whole day recovering the
suddenly failing tests. Most are now
OK, but some are still failing. :(
Why this all started to happen, is
completely unclear.

**Comment by stsp** [comment]
Ah, I see:
```
--- -	2023-11-16 13:03:20.545796571 +0000
+++ /home/runner/work/fdpp/fdpp/test-dosemu/test-imagedir/libi86-test/tests/testsuite.dir/at-groups/3/stdout	2023-11-16 13:03:20.539220361 +0000
@@ -1,2 +1,3 @@
+failed to open /home/runner/work/fdpp/fdpp/test-dosemu/installed-fdpp/lib/fdpp/fdppkrnl.34.10.elf
 Hello world!
 
3. metacheck.at:38: 3. dosemu (metacheck.at:38): FAILED (metacheck.at:41)
```
Good logging! :)

**Comment by stsp** [comment]
No, that's just a warning.
It doesn't understand them indeed,
but they are consumed by the sub-configures
in a plugin dirs.
I still don't know why all the hell broke,
but I think the remaining tests are now
recovered too. Though its quite annoying
to suddenly have to recover every test
one-by-one.

**Comment by stsp** [comment]
E.g. coopth started to crash: 3427ffa63
Hell knows why, I haven't touched it
for ages.
Alternative kernel locations have never
actually being probed:
https://github.com/dosemu2/dosemu2/commit/f3dd2fe979d61b2d2d2cdf601bbfb37e39c913d0
And so on.
Very strange.

**Comment by stsp** [comment]
OK, tests finally passed.
After 4 patches to dosemu2 and
4 to fdpp...
:1234:

**Comment by stsp** [comment]
And one more interesting thing:
in dosemu2 repo, nothing ever failed!
All failures started to happen only here.

**Comment by andrewbird** [comment]
>And one more interesting thing:
in dosemu2 repo, nothing ever failed!
All failures started to happen only here.

It looks like https://github.com/dosemu2/dosemu2/commit/60898a832d578ace44e4a5f6ab52b0495aea8bf4 changed it to use a standard FDPP installation directory.
