### ISSUE TITLE
NASM-SEGELF Problem

### ISSUE THREAD

**Issue by sidiqmuhammad** [dosemu2/fdpp#243]
Hi.. thanks for reading my issue,,
im sorry for my terrible english, and yes i need your help
i already clone fdpp in my debian 12, when i run `make install` i got something like this :
```
make -C fdpp install
make[1]: Entering directory '/home/user/Downloads/fdpp/fdpp'
make -C kernel
make[2]: Entering directory '/home/user/Downloads/fdpp/fdpp/kernel'
nasm-segelf -DWITHFAT32 -i/home/user/Downloads/fdpp/fdpp/kernel/../hdr/ -DXCPU=186 -DFDPP -i/home/user/Downloads/fdpp/kernel -i/home/user/Downloads/fdpp/hdr -f elf32 -o kernel.o /home/user/Downloads/fdpp/kernel/kernel.asm
bash: line 1: nasm-segelf: command not found
make[2]: *** [makefile:89: kernel.o] Error 127
make[2]: Leaving directory '/home/user/Downloads/fdpp/fdpp/kernel'
make[1]: *** [makefile:61: fdppkrnl.35.10.elf] Error 2
make[1]: Leaving directory '/home/user/Downloads/fdpp/fdpp'
make: *** [makefile:6: install] Error 2
```
but i also already installed nasm, im not really expert in linux
did i miss something?

**Comment by sidiqmuhammad** [comment]
I installed `nasm-segelf.rb` with `brew` 
this fix my problem

**Comment by stsp** [comment]
Wow, you were quick. :)
Does debian-12 have homebrew
out of the box? Even on ubuntu
I can't do `brew install ./nasm-segelf.rb`
because homebrew is not there.
So I actually thought this is a problem
for our user, but it appears not? :)

**Comment by sidiqmuhammad** [comment]
> Wow, you were quick. :) Does debian-12 have homebrew out of the box? Even on ubuntu I can't do `brew install ./nasm-segelf.rb` because homebrew is not there. So I actually thought this is a problem for our users, but it appears not? :)

no, i install homebrew manually, but r now i got another problem, maybe you can help me with my new issue?
[https://github.com/dosemu2/dosemu2/issues/2129](https://github.com/dosemu2/dosemu2/issues/2129)
